const mongoose = require("mongoose");

const admepassSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  sn:{type:Number,required:true},
  cid:{type:Number,required:true},
  compoundName: { type: String, required: true },
  modecule: { type: String, required: true },
  canonical: { type: String, required: true },
  formula: { type: String, required: true },
  mW:{type:Number,required:true},
  heavyaton:{type:Number,required:true},
  aromaticHeavyAtoms: { type: String, required: true },
  fractionCsp3: { type: String, required: true },
  rotatablebonds: { type: String, required: true },
  hbondacceptors: { type: String, required: true },
  hbonddonors: { type: String, required: true },
  mR: { type: String, required: true },
  tPSA: { type: String, required: true },
  iLOGP: { type: String, required: true },
  xLOGP3: { type: String, required: true },
  wLOGP: { type: String, required: true },
  mLOGP: { type: String, required: true },
  SilicosITLogP: { type: String, required: true },
  ConsensusLogP: { type: String, required: true },
  ESOLLogS: { type: String, required: true },
  ESOLSolubilityMG: { type: String, required: true },
  ESOLSolubilityMOL: { type: String, required: true },
  ESOLClass: { type: String, required: true },
  AliLogS: { type: String, required: true },
  AliSolubilityMG: { type: String, required: true },
  AliSolubilitydMOL: { type: String, required: true },
  AliClass: { type: String, required: true },
  SilicosITLogSw: { type: String, required: true },
  SilicosITSolubilityMG: { type: String, required: true },
  SilicosITSolubilityMOL: { type: String, required: true },
  SilicosITClass: { type: String, required: true },
  GIabsorption: { type: String, required: true },
  BBBpermeant: { type: String, required: true },
  Pgpsubstrate: { type: String, required: true },
  CYP1A2inhibitor: { type: String, required: true },
  CYP2C19inhibitor: { type: String, required: true },
  CYP2C9inhibitor: { type: String, required: true },
  CYP2D6inhibitorl: { type: String, required: true },
  CYP3A4inhibitor: { type: String, required: true },
  logKp: { type: String, required: true },
  Lipinskiviolations: { type: String, required: true },
  Ghoseviolations: { type: String, required: true },
  Veberviolations: { type: String, required: true },
  Eganviolations: { type: String, required: true },
  Mueggeviolations: { type: String, required: true },
  BioavailabilityScore: { type: String, required: true },
  PAINSalerts: { type: String, required: true },
  Brenkalerts: { type: String, required: true },
  Leadlikenessviolations: { type: String, required: true },
  SyntheticAccessibility: { type: String, required: true },
});

module.exports = mongoose.model("ADMEpass", admepassSchema);
